config/routes.rb
Rails.application.routes.draw do

  resources :transports, except:[:show]

  resources :wishes, except:[:show]

  resources :songs, except:[:show]

  resources :approvals, only:[:new, :create, :index]

  resources :hitchhikes, except:[:show]

  root :to => "static_pages#home"
  get 'hotels' => 'static_pages#hotels'
  get 'getting_there' => 'static_pages#getting_there'
  get 'program' => 'static_pages#program'

  get 'gallery/:id' => 'static_pages#gallery'
  get 'gallery' => 'static_pages#gallery'

  get 'wedding' => 'static_pages#wedding'
  

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  self.per_page = 5
  
  auto_strip_attributes :name, :nullify => false
  auto_strip_attributes :content, :nullify => false
  
	validates :content, length:{minimum:3, maximum:512}
	validates :name, length:{minimum:3, maximum:64}
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]

  def index
    @wishes = Wish.paginate(:page => params[:page]).order("created_at DESC")
  end

  def show
  end

  def new
    @wish = Wish.new
  end

  def edit
  end

  def create
    @wish = Wish.new(wish_params)

    respond_to do |format|
      if verify_recaptcha(:model => @wish, :message => "טעות באימות המספרים") && @wish.save
        format.html { redirect_to wishes_path, notice: 'תודה על הברכה!' }
        format.json { render :show, status: :created, location: @wish }
      else
        format.html { render :new }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if verify_recaptcha(:model => @wish, :message => "טעות באימות המספרים") && @wish.update(wish_params)
        format.html { redirect_to wishes_path, notice: 'הברכה עודכנה' }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @wish.destroy
    respond_to do |format|
      format.html { redirect_to wishes_url, notice: 'Wish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wish_params
      params.require(:wish).permit(:content, :name)
    end
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/wishes/_form.html.haml
= bootstrap_form_for @wish do |f|
  = f.text_area :content, label:'הברכה'
  = f.text_field :name, label:'שם'

  = recaptcha_tags ajax:true

  = f.submit "שלח ברכה", class: "btn btn-success"

app/views/wishes/edit.html.haml
%h1 ערוך ברכה
= render 'form'
= link_to 'חזור', wishes_path

app/views/wishes/index.html.haml
%h1 ספר אורחים

= will_paginate @wishes, renderer: BootstrapPagination::Rails

-@wishes.each do |w|
  .wish
    =simple_format(w.content)
    .from
      מאת
      = w.name 
      %span{dir:'rlt', float:'left'}= "(" + w.created_at.strftime("%d-%m") + ")"
      .edit
        = link_to 'ערוך', edit_wish_path(w)

= will_paginate @wishes, renderer: BootstrapPagination::Rails

%br

= button_to 'הוסף ברכה', new_wish_path, class:"btn btn-primary", method: "get"

app/views/wishes/new.html.haml
%h1 הוסף ברכה

= render 'form'

= link_to 'חזור', wishes_path

app/views/wishes/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @wish.content
%p
  %b Name:
  = @wish.name

= link_to 'Edit', edit_wish_path(@wish)
\|
= link_to 'Back', wishes_path