config/routes.rb
Rails.application.routes.draw do

  resources :transports, except:[:show]

  resources :wishes, except:[:show]

  resources :songs, except:[:show]

  resources :approvals, only:[:new, :create, :index]

  resources :hitchhikes, except:[:show]

  root :to => "static_pages#home"
  get 'hotels' => 'static_pages#hotels'
  get 'getting_there' => 'static_pages#getting_there'
  get 'program' => 'static_pages#program'

  get 'gallery/:id' => 'static_pages#gallery'
  get 'gallery' => 'static_pages#gallery'

  get 'wedding' => 'static_pages#wedding'
  

end

app/models/transport.rb
class Transport < ActiveRecord::Base
  auto_strip_attributes :name, :nullify => false
  auto_strip_attributes :comments, :nullify => false 
	validates :direction, :inclusion => 0..2
  
  def direction_names
    ['הלוך ושוב','רק הלוך','רק חזור']
  end

  def human_direction_name
    direction_names[self.direction]
  end

  after_initialize :default_values

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ['שם', 'כיוון', 'טלפון', 'הערות']
      all.each do |t|
        csv << [t.name, t.human_direction_name, t.phone, t.comments]
      end
    end
  end

  private
  def default_values
    self.direction ||= 0
  end


end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :set_transport, only: [:edit, :update, :destroy]

  # GET /transports
  # GET /transports.json
  def index
    respond_to do |format| 
      format.html {
        @transports = Transport.all
      }
      format.csv { send_data Transport.to_csv }
    end
  end

  def new
    @transport = Transport.new
  end

  def edit
  end

  def create
    @transport = Transport.new(transport_params)

    respond_to do |format|
      if @transport.save
        format.html { redirect_to transports_url, notice: 'בקשתך נרשמה' }
        format.json { render :show, status: :created, location: @transport }
      else
        format.html { render :new }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @transport.update(transport_params)
        format.html { redirect_to transports_url, notice: 'הרשומה עודכנה' }
        format.json { render :show, status: :ok, location: @transport }
      else
        format.html { render :edit }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transport.destroy
    respond_to do |format|
      format.html { redirect_to transports_url, notice: 'הרשומה נמחקה.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transport
      @transport = Transport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transport_params
      params.require(:transport).permit(:name, :direction, :comments, :phone)
    end
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/transports/_form.html.haml
= bootstrap_form_for @transport do |f|
  = f.text_field :name, label:'שם'
  = f.text_field :phone, label:'טלפון'
  = f.text_field :comments, label:'הערות'

  = f.form_group :song_type do
    - @transport.direction_names.each.with_index do |t,i|
      = f.radio_button :direction, i, label: t
  
  = recaptcha_tags
  = f.submit "שלח", class: "btn btn-success"
  

app/views/transports/edit.html.haml
%h1 ערוך פרטים

= render 'form'

= link_to 'חזור', transports_path

app/views/transports/index.html.haml
%h1 הסעה מהמרכז
%p
  ההסעה מהמרכז תצא <strong>בשעה חמש</strong> מרידינג בתל אביב למעלה גמלא ותחזור בחזרה בלילה.<br/>
  לפרטים נוספים ולכל שאלה ניתן לדבר עם עמית: 054-5459456.
%p
  על מנת שנוכל לארגן את ההזמנה, אנא הרשמו עד יום שלישי ה2/9:

= button_to 'הרשמה להסעה', new_transport_path, class:"btn btn-primary", method: :get
%br

%table.table.table-striped
  %tr
    %th שם
    %th כיוון
    %th טלפון
    %th הערות
    %th

  - @transports.each do |t|
    %tr
      %td
        %strong= t.name
      %td= t.human_direction_name
      %td= t.phone
      %td= t.comments
      %td= link_to 'ערוך', edit_transport_path(t)


%ul.list-inline{style:"padding-right:0px;"}
  -# %li= button_to 'הרשמה להסעה', new_transport_path, class:"btn btn-primary", method: :get
  %li= button_to 'CSV', transports_path(format: "csv"), class:"btn btn-primary", method: :get

app/views/transports/new.html.haml
%h1 הרשמה להסעה

= render 'form'

= link_to 'חזור', transports_path