config/routes.rb
Rails.application.routes.draw do

  resources :transports, except:[:show]

  resources :wishes, except:[:show]

  resources :songs, except:[:show]

  resources :approvals, only:[:new, :create, :index]

  resources :hitchhikes, except:[:show]

  root :to => "static_pages#home"
  get 'hotels' => 'static_pages#hotels'
  get 'getting_there' => 'static_pages#getting_there'
  get 'program' => 'static_pages#program'

  get 'gallery/:id' => 'static_pages#gallery'
  get 'gallery' => 'static_pages#gallery'

  get 'wedding' => 'static_pages#wedding'
  

end

app/models/song.rb
class Song < ActiveRecord::Base
  self.per_page = 20

  auto_strip_attributes :name, :nullify => false
  auto_strip_attributes :artist, :nullify => false
  validates :name, presence: true, allow_blank: false 
	validates :song_type, :inclusion => 0..2
  
  def song_type_names
    ['ריקודים','קבלת פנים','חופה']
  end

  def human_song_type
    song_type_names[self.song_type]
  end

  after_initialize :default_values

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ['שם', 'מבצע', 'סוג']
      all.each do |song|
        csv << [song.name, song.artist, song.human_song_type]
      end
    end
  end

  private
    def default_values
      self.song_type ||= 0
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format| 
      format.html {
        @songs = Song.paginate(:page => params[:page]).order("created_at DESC")
      }
      format.csv { send_data Song.all.to_csv }
    end
  end

  def new
    @song = Song.new
  end

  def edit
  end

  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to songs_url, notice: 'בקשתך התקבלה' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to songs_url, notice: 'הבקשה עודכנה' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'הבקשה נמחלקה' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :artist, :song_type)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.haml
= bootstrap_form_for @song do |f|
  = f.text_field :name, label:'שם השיר'
  = f.text_field :artist, label:'מבצע'

  = f.form_group :song_type do
    - @song.song_type_names.each.with_index do |t,i|
      = f.radio_button :song_type, i, label: t
  
  = recaptcha_tags
  = f.submit "שלח", class: "btn btn-success"
  

app/views/songs/edit.html.haml
%h1 ערוך שיר

= render 'form'

= link_to 'חזור', songs_path

app/views/songs/index.html.haml
%h1 רשימת שירים
%p
  בקשות לשירים - אתם מוזמנים לבקש את השיר האהוב עליכם
  %sup
    %i.fa.fa-asterisk{style:"font-size:6px;"}

= button_to 'בקש שיר', new_song_path, class:"btn btn-primary", method: :get
%br

= will_paginate @songs, renderer: BootstrapPagination::Rails

%table.table.table-striped
  %tr
    %th שם
    %th מבצע
    %th סוג השיר
    %th

  - @songs.each do |song|
    %tr
      %td
        %strong= song.name
      %td= song.artist
      %td= song.human_song_type
      %td= link_to 'ערוך', edit_song_path(song)


%p#disclaimer
  %sup
    %i.fa.fa-asterisk
  המתקלט אינו מתחייב לרשימת השירים הנל

%ul.list-inline{style:"padding-right:0px;"}
  %li= button_to 'בקש שיר', new_song_path, class:"btn btn-primary", method: :get
  %li= button_to 'CSV', songs_path(format: "csv"), class:"btn btn-primary", method: :get

app/views/songs/new.html.haml
%h1 בקש שיר

= render 'form'

= link_to 'חזור', songs_path

app/views/songs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @song.name
%p
  %b Artist:
  = @song.artist
%p
  %b Song type:
  = @song.song_type

= link_to 'Edit', edit_song_path(@song)
\|
= link_to 'Back', songs_path