config/routes.rb
Rails.application.routes.draw do

  resources :transports, except:[:show]

  resources :wishes, except:[:show]

  resources :songs, except:[:show]

  resources :approvals, only:[:new, :create, :index]

  resources :hitchhikes, except:[:show]

  root :to => "static_pages#home"
  get 'hotels' => 'static_pages#hotels'
  get 'getting_there' => 'static_pages#getting_there'
  get 'program' => 'static_pages#program'

  get 'gallery/:id' => 'static_pages#gallery'
  get 'gallery' => 'static_pages#gallery'

  get 'wedding' => 'static_pages#wedding'
  

end

app/models/hitchhike.rb
class Hitchhike < ActiveRecord::Base
  # phone, hour, comments, taking, from, name 
  
  auto_strip_attributes :name, :nullify => false
  auto_strip_attributes :phone, :nullify => false
  auto_strip_attributes :hour, :nullify => true
  auto_strip_attributes :from, :nullify => false
  auto_strip_attributes :comments, :nullify => true
  
	validates :name, presence: true
	validates :phone, presence: true
	validates :from, presence: true

end

app/controllers/hitchhikes_controller.rb
class HitchhikesController < ApplicationController
  before_action :set_hitchhike, only: [:show, :edit, :update, :destroy]

  def index
    @hitchhikes = Hitchhike.all
  end

  def new
    @hitchhike = Hitchhike.new(taking:true)
  end

  def edit
  end

  def create
    @hitchhike = Hitchhike.new(hitchhike_params)

    respond_to do |format|
      if verify_recaptcha(:model => @hitchhike, :message => "טעות באימות המספרים") && @hitchhike.save
        format.html { redirect_to hitchhikes_url, notice: 'הטרמפ נוצר בהצלחה' }
        format.json { render :show, status: :created, location: @hitchhike }
      else
        format.html { render :new }
        format.json { render json: @hitchhike.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if verify_recaptcha(:model => @hitchhike, :message => "טעות באימות המספרים") && @hitchhike.update(hitchhike_params)
        format.html { redirect_to hitchhikes_url, notice: 'הטרמפ עודכן בהצלחה' }
        format.json { render :show, status: :ok, location: @hitchhike }
      else
        format.html { render :edit }
        format.json { render json: @hitchhike.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @hitchhike.destroy
    respond_to do |format|
      format.html { redirect_to hitchhikes_url, notice: 'Hitchhike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hitchhike
      @hitchhike = Hitchhike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hitchhike_params
      params.require(:hitchhike).permit(:name, :phone, :from, :hour, :comments, :taking)
    end
end

app/helpers/hitchhikes_helper.rb
module HitchhikesHelper
end

app/views/hitchhikes/_form.html.haml
= bootstrap_form_for @hitchhike do |f|
  = f.text_field :name, label:'שם'
  = f.text_field :phone, label:'טלפון / מייל'
  = f.text_field :from, label:'יוצא מיישוב'
  = f.text_field :hour, label:'שעת יציאה'
  = f.text_field :comments, label:'הערות'
  = f.form_group :taking do
    = f.radio_button :taking, true, label: "מציע טרמפ"
    = f.radio_button :taking, false, label: "מחפש טרמפ"

  = recaptcha_tags ajax:true

  = f.submit "צור טרמפ", class: "btn btn-success"

app/views/hitchhikes/edit.html.haml
%h1 ערוף טרמפ

= render 'form'

= link_to 'חזור', hitchhikes_path

app/views/hitchhikes/index.html.haml
%h1 לוח טרמפים

%h3{style:"color:red;"} שימו לב! כנראה שתהיה הסעה מהמרכז לגולן ובחזרה

%br

%table.table.table-striped
  %tr
    %th שם
    %th טלפון/מייל
    %th יוצא מישוב
    %th שעה
    %th הערות
    %th לוקח / מצטרף
    %th

  - @hitchhikes.each do |hitchhike|
    %tr
      %td= hitchhike.name
      %td= hitchhike.phone
      %td= hitchhike.from
      %td= hitchhike.hour
      %td= hitchhike.comments
      %td= hitchhike.taking ? 'לוקח' : 'מצטרף'
      %td= link_to 'ערוך', edit_hitchhike_path(hitchhike)

%br

= button_to 'בקש / הצע טרמפ', new_hitchhike_path, class:"btn btn-primary", method: "get"

app/views/hitchhikes/new.html.haml
%h1 צור טרמפ חדש

= render 'form'

= link_to 'חזור', hitchhikes_path

app/views/hitchhikes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @hitchhike.name
%p
  %b Phone:
  = @hitchhike.phone
%p
  %b From:
  = @hitchhike.from
%p
  %b Hour:
  = @hitchhike.hour
%p
  %b Comments:
  = @hitchhike.comments
%p
  %b Taking:
  = @hitchhike.taking

= link_to 'Edit', edit_hitchhike_path(@hitchhike)
\|
= link_to 'Back', hitchhikes_path